- name: Create secrets directory
  file:
    path: ".secrets"
    state: directory


- name: Create secrets
  template:
    src: "{{item}}"
    dest: ".secrets/{{item}}"
    mode: '0600'
  with_items:
    - id_rsa
    - id_rsa.pub
